---
- name: Build server
  hosts: build
  become: yes
  become_method: hmthanh

  vars:
    mvn_home: /usr/share/maven

  tasks:
    - name: Pull code from github
      git:
        repo: git@github.com:hmthanh/simple-java-maven-app.git
        dest: /home/hmthanh/simple-java-maven-app
