---
- name: Deploy server
  hosts: deploy
  become: yes
  become_user: hmthanh

  vars:
    mvn_home: /usr/share/maven

  tasks:
    - name: Pull image from registry
      shell: docker pull 192.168.229.134:5000/example

    - name: Run images
      shell: docker run -d -p 8080:8080 192.168.229.134:5000/example
