---
- hosts: build
  become: yes
  become_user: hmthanh

  vars:
    mvn_home: /usr/share/maven

  tasks:
    - name: Run Maven in {{ mvn_home }}
      shell: mvn -Dmaven.test.failure.ignore clean package

    - name: Create image
      shell: docker build -t hostvars['build']['ansible_ssh_host']:5000/example .

    - name: Push image to registry
      shell: docker push hostvars['build']['ansible_ssh_host']:5000/example
